services:
  mysql:
    image: "mysql:latest"
    environment:
      - "MYSQL_DATABASE=park_api"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_USER=user"
    ports:
      - "3307:3306"
